# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7e7009e6ae3e638341106533a175b5eb0f964b648c3a63ab9a17bbe940b64bf3d3e5b0043ed0e08c93aac208143528e8b0bab334c3309ad286a836f8ea423fa6

test:
  secret_key_base: b65ab9570927c931f646d302133446e0a82842216314fa5356db7d9a5103c296e39d2008dbe7c3b24098abcab2e41fab12ea6776aad26381da3d81d393bbf3ab

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
